# committed configuration (https://github.com/crate-ci/committed)

line_length = 0
subject_length = 0
subject_capitalized = false
subject_not_punctuated = true
imperative_subject = true
merge_commit = true
no_fixup = true
no_wip = true

style = "conventional"

# allowed commit types
allowed_types = [
  "build",
  "chore",
  "ci",
  "docs",
  "feat",
  "fix",
  "refactor",
  "revert",
  "style",
  "test",
]

# allowed commit scopes
allowed_scopes = [
  "database",
]
