# typos configuration (https://github.com/crate-ci/typos)

[default]
extend-ignore-re = [
  # ignore lines with trailing "spellchecker:disable-line"
  "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
  # ignore blocks with "spellchecker:<on|off>"
  "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]

[default.extend-words]
eaasi = "eaasi"
